### PR TITLE
adds a site message component with message & optional warning icon/color

### PR DESCRIPTION
**Pull request by andycochran**
image

### CODE REVIEW

**Comment by allthesignals** [comment]
Thanks for doing this! I think it's resolved now.

**Comment by rtblair** [comment]
@allthesignals can we leave this in but commented out? Or put a toggle somewhere so that it can be enabled in the future?

**Comment by allthesignals** [comment]
@rtblair you bet!

**Comment by allthesignals** [comment]
Todo: comment out and make available for later

**Comment by andycochran** [comment]
I pushed changes for nixing the message and keeping the component (with inline docs). But It seems GitHub is having technical difficulties.

**Comment by allthesignals** [comment]
@andycochran did your changes get successfully pushed? I know GH was out...

**Comment by allthesignals** [comment]
@andycochran lemme know so I can merge please.

**Comment by andycochran** [comment]
Yup. Looks like all my local work is there now.

**Pull request merged**
