### PR TITLE
919 Sort Upcoming Assignments by System Target Certification Date

### PR DESCRIPTION
**Pull request by godfreyyeung**
Addresses #919 

The merge of this PR should be coordinated with the merge of PR https://github.com/NYCPlanning/labs-zap-api/pull/110

### CODE REVIEW

**Comment by allthesignals** [comment]
@godfreyyeung did you get your question answered for this? Should this be a full PR?

**Comment by godfreyyeung** [comment]
> @godfreyyeung did you get your question answered for this? Should this be a full PR?

No, haven't yet. @hannahkates Did we ever get to talk to Aline about this?

**Comment by hannahkates** [comment]
@godfreyyeung We confirmed that dcp_certificationtargetdate is the correct field to use. However, the issue has been updated to include "Prefiled" projects

**Comment by allthesignals** [comment]
Closing for now — let's revisit later

**Pull request closed without merging**
