### PR TITLE
Fixturize mirage

### PR DESCRIPTION
**Pull request by allthesignals**
This PR turns the generated scenario into static data in order to improve load time of development environment and to encourage more use of acceptance tests to check for correct handling of scenarios 

Addresses #730

### CODE REVIEW

**Comment by godfreyyeung** [comment]
Just noticed some of the raw data contains factory generated data where it shouldn't. e.g. disposition.communityboardrecommendation and disposition.consideration has mirage data filled in.  I should remove these values before merging this, or do it in another issue/pr and regenerate this raw data.

**Comment by allthesignals** [comment]
@godfreyyeung yeah let me take a look at these tests... not sure what's up!

**Comment by allthesignals** [comment]
> Just noticed some of the raw data contains factory generated data where it shouldn't. e.g. disposition.communityboardrecommendation and disposition.consideration has mirage data filled in. I should remove these values before merging this, or do it in another issue/pr and regenerate this raw data.

I don't understand the issue you're bringing up

**Comment by godfreyyeung** [comment]
> > Just noticed some of the raw data contains factory generated data where it shouldn't. e.g. disposition.communityboardrecommendation and disposition.consideration has mirage data filled in. I should remove these values before merging this, or do it in another issue/pr and regenerate this raw data.
> 
> I don't understand the issue you're bringing up

nvm, I fixed it 😁

**Pull request merged**
