### PR TITLE
1559 Add informational modal to ZAP Search homepage

### PR DESCRIPTION
**Pull request by dhochbaum-dcp**
- [x] Add a modal that users see when they visit ZAP Search that directs them to the new subscriptions page
- [x] Designs can be found [here](https://www.figma.com/design/1HrOm1tkJ3lowQhrSRkPLs/ZAP-Listserv%3A-Wireframes-and-User-Stories?node-id=353-74&node-type=frame&t=U8AKDO14tXxrlzv8-0) but we don't need to follow designs exactly if there is an existing modal component in ZAP Search we can use. However, copy should be as seen in designs
- [x] User can dismiss the modal and it doesn't reappear when navigating between pages in the app
- [x] Modal has "Do not show this message again" checkbox. If checked, the user should not see the message again when they visit the app again in the same browser.
- [x] Link to `/subscribe" page

The route to the subscribe page does not exist, and so linking to the subscribe route completely breaks the site.  Once subscribe route exists, I can switch the link, and it will complete #1559

### CODE REVIEW

**Comment by TylerMatteo** [comment]
@dhochbaum-dcp The code lgtm but can you get this up in a preview deploy for @jessicashanshanhuang?

**Comment by dhochbaum-dcp** [comment]
> @dhochbaum-dcp The code lgtm but can you get this up in a preview deploy for @jessicashanshanhuang?

One already exists: https://deploy-preview-1561--labs-zap.netlify.app/projects

**Comment by dhochbaum-dcp** [comment]
> Hey @dhochbaum-dcp, the module looks great!
> 
> I was wondering is it possible to change the background overlay color to `#F1F2F4` and the module background color to `#FBF0E9`?

No problem @jessicashanshanhuang - the deploy preview is updated with the new colors.

**Comment by jessicashanshanhuang** [comment]
@dhochbaum-dcp the new colors look great! 

I also noticed that the module is not centered vertically (it is centered horizontally), so once that is fixed the positioning should be good to go. 

For the box shadow color, decrease the opacity to around 70%.

**Comment by dhochbaum-dcp** [comment]
> @dhochbaum-dcp the new colors look great!
> 
> I also noticed that the module is not centered vertically (it is centered horizontally), so once that is fixed the positioning should be good to go.
> 
> For the box shadow color, decrease the opacity to around 70%.

I've centered the module vertically.  Can you please clarify what you mean by the box shadow color?  The box-shadow for the modal is currently `box-shadow: 0 0 0 0.25rem rgba(0, 0, 0, 0.1);`.  If I change the 0.1 to 0.7, it looks like the below:
image

**Comment by jessicashanshanhuang** [comment]
> I've centered the module vertically. Can you please clarify what you mean by the box shadow color? The box-shadow for the modal is currently `box-shadow: 0 0 0 0.25rem rgba(0, 0, 0, 0.1);`. If I change the 0.1 to 0.7, it looks like the below: image

I see, I was trying to replicate the softer blur drop shadow in the wireframe by adjusting the opacity.

 I think the best choice would be to go back to `box-shadow: 0 0 0 0.25rem rgba(0, 0, 0, 0.1)` but specify the shadow to only appear the bottom of the box and have a blur. Also the positioning should be shifted slightly down (I think we have it on 4px on the design). 

Screenshot 2024-10-30 at 1 26 10 PM
Screenshot 2024-10-30 at 1 26 45 PM

**Comment by jessicashanshanhuang** [comment]
@dhochbaum-dcp Looks good to go 🫡

**Review by TylerMatteo — APPROVED** [review]

**Review by TylerMatteo — APPROVED** [review]

**Pull request merged**
